{{- if .Values.networking.service.main.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "technitium.fullname" . }}
  labels:
    {{- include "technitium.labels" . | nindent 4 }}
spec:
  type: {{ .Values.networking.service.main.type }}
  selector:
    {{- include "technitium.selectorLabels" . | nindent 4 }}
  ports:
    {{- range $name, $port := .Values.networking.service.main.ports }}
    {{- if ne (toString $port.enabled) "false" }}
    - name: {{ $name }}
      port: {{ $port.port }}
      targetPort: {{ $name }}
      protocol: {{ $port.protocol }}
    {{- end }}
    {{- end }}
{{- end }}
{{- if .Values.networking.service.dns.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "technitium.fullname" . }}-dns
  labels:
    {{- include "technitium.labels" . | nindent 4 }}
spec:
  type: {{ .Values.networking.service.dns.type }}
  selector:
    {{- include "technitium.selectorLabels" . | nindent 4 }}
  ports:
    {{- range $name, $port := .Values.networking.service.dns.ports }}
    {{- if ne (toString $port.enabled) "false" }}
    - name: {{ $name }}
      port: {{ $port.port }}
      targetPort: {{ $name }}
      protocol: {{ $port.protocol }}
    {{- end }}
    {{- end }}
{{- end }}
