apiVersion: v1
kind: Service
metadata:
  name: {{ include "technitium.fullname" . }}
  labels:
    {{- include "technitium.labels" . | nindent 4 }}
spec:
  type: {{ .Values.networking.service.type }}
  selector:
    {{- include "technitium.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.networking.service.port }}
      targetPort: http
      protocol: TCP
    - name: dns-udp
      port: {{ .Values.dnsPorts.dns }}
      targetPort: dns-udp
      protocol: UDP
    - name: dns-tcp
      port: {{ .Values.dnsPorts.dns }}
      targetPort: dns-tcp
      protocol: TCP
    - name: dns-dot
      port: {{ .Values.dnsPorts.dot }}
      targetPort: dns-dot
      protocol: TCP
    - name: dns-doh
      port: {{ .Values.dnsPorts.doh }}
      targetPort: dns-doh
      protocol: TCP
    - name: dns-https
      port: {{ .Values.dnsPorts.https }}
      targetPort: dns-https
      protocol: TCP
