command_line:
  - sensor:
      name: "GitOps Repo Name"
      unique_id: gitops_repo_name
      command: "cat /config/.gitops/state/gitops_repo_name"
      scan_interval: 3600
  - sensor:
      name: "GitOps Repo URL"
      unique_id: gitops_repo_url
      command: "cat /config/.gitops/state/gitops_repo_url"
      scan_interval: 3600
  - sensor:
      name: "GitOps Sync Ref"
      unique_id: gitops_sync_ref
      command: "cat /config/.gitops/state/gitops_sync_ref"
      scan_interval: 3600
  - sensor:
      name: "GitOps Last Sync"
      unique_id: gitops_last_sync
      command: "cat /config/.gitops/state/gitops_last_sync"
      device_class: timestamp
      scan_interval: 3600
