apiVersion: v2
name: python-matter-server
description: A Helm chart for deploying the Python Matter Server on Kubernetes
type: application
version: 1.0.1
keywords:
  - home-assistant
  - matter
maintainers:
  - name: junpeng-jp
    url: https://github.com/junpeng-jp
