{{- if .Values.homeAssistant.config.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "home-assistant.fullname" . }}-config
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
data:
  configuration.yaml: |
    {{- include "home-assistant.configYaml" . | nindent 4 }}
{{- end }}
{{- if .Values.homeAssistant.packages.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "home-assistant.fullname" . }}-packages
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
data:
  {{- range $filename, $content := .Values.homeAssistant.packages.files }}
  {{ $filename }}: |
    {{- $content | nindent 4 }}
  {{- end }}
{{- end }}
