{{- if include "home-assistant.gitopsSignersEnabled" . }}
{{- $gitops := .Values.homeAssistant.initContainer.tasks.gitops }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "home-assistant.configmapName.gitopsSigners" . }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
data:
  {{- range $gitops.repos }}
  {{- if .allowedSigners }}
  {{ .name }}: |
    {{- .allowedSigners | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
