{{- if and .Values.homeAssistant.config.enabled (not .Values.homeAssistant.config.existingConfigMap) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "home-assistant.fullname" . }}-config
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
data: {}
{{- end }}
{{- if and .Values.homeAssistant.packages.enabled (not .Values.homeAssistant.packages.existingConfigMap) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "home-assistant.fullname" . }}-packages
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
data: {}
{{- end }}
{{- if and .Values.homeAssistant.themes.enabled (not .Values.homeAssistant.themes.existingConfigMap) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "home-assistant.fullname" . }}-themes
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
data: {}
{{- end }}
