{{- if include "home-assistant.gitopsEnabled" . }}
{{- $gitops := .Values.homeAssistant.initContainer.tasks.gitops }}
{{- $isGitOpsSSH := include "home-assistant.isGitOpsSSH" . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "home-assistant.configmapName.gitops" . }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
data:
  gitops-setup: |-
    {{- .Files.Get "scripts/gitops-setup" | nindent 4 }}
  gitops: |-
    {{- .Files.Get "scripts/gitops" | nindent 4 }}
  {{- $repoNames := list -}}
  {{- range $gitops.repos -}}{{- $repoNames = append $repoNames .name -}}{{- end }}
  repos: {{ join "\n" $repoNames | quote }}
  {{- if $isGitOpsSSH }}
  knownHosts: {{ $gitops.ssh.knownHosts | quote }}
  {{- $sshRepoNames := list -}}
  {{- range $gitops.repos -}}
    {{- if regexMatch `^(git@|ssh://)` (.url | default "") -}}
      {{- $sshRepoNames = append $sshRepoNames .name -}}
    {{- end -}}
  {{- end }}
  ssh-repos: {{ join "\n" $sshRepoNames | quote }}
  {{- end }}
  {{- range $gitops.repos }}
  {{- if .allowedSigners }}
  allowed-signers-{{ .name }}: {{ .allowedSigners | quote }}
  {{- end }}
  {{- end }}
{{- end }}
