{{- if .Values.ingress.traefik.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "home-assistant.fullname" . }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
spec:
  entryPoints:
    {{- toYaml .Values.ingress.traefik.entryPoints | nindent 4 }}
  routes:
    {{- range .Values.ingress.traefik.hostnames }}
    - match: Host(`{{ . }}`)
      services:
        - name: {{ include "home-assistant.fullname" $ }}
          port: http
      {{- with $.Values.ingress.traefik.middlewares }}
      middlewares:
        {{- range . }}
        - name: {{ .name }}
          {{- if .namespace }}
          namespace: {{ .namespace }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- if .Values.ingress.traefik.tls.enabled }}
  tls:
    {{- if .Values.ingress.traefik.tls.secretName }}
    secretName: {{ .Values.ingress.traefik.tls.secretName }}
    {{- end }}
    {{- if .Values.ingress.traefik.tls.certResolver }}
    certResolver: {{ .Values.ingress.traefik.tls.certResolver }}
    {{- end }}
  {{- end }}
{{- end }}
