{{- $svcType := "" -}}
{{- $ports := dict -}}
{{- if .Values.networking.service.clusterIp.enabled -}}
{{-   $svcType = "ClusterIP" -}}
{{-   $ports = .Values.networking.service.clusterIp.ports -}}
{{- else if .Values.networking.service.loadBalancer.enabled -}}
{{-   $svcType = "LoadBalancer" -}}
{{-   $ports = .Values.networking.service.loadBalancer.ports -}}
{{- end -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "home-assistant.fullname" . }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
spec:
  type: {{ $svcType }}
  selector:
    {{- include "home-assistant.selectorLabels" . | nindent 4 }}
  ports:
    {{- range $name, $port := $ports }}
    {{- if ne (toString $port.enabled) "false" }}
    - name: {{ $name }}
      port: {{ $port.port }}
      targetPort: {{ $name }}
      protocol: {{ $port.protocol }}
    {{- end }}
    {{- end }}
