{{- range $svcName := keys .Values.networking.service | sortAlpha }}
{{- $svc := index $.Values.networking.service $svcName }}
{{- if $svc.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ if eq $svcName "app" }}{{ include "home-assistant.fullname" $ }}{{ else }}{{ printf "%s-%s" (include "home-assistant.fullname" $) $svcName }}{{ end }}
  labels:
    {{- include "home-assistant.labels" $ | nindent 4 }}
spec:
  type: {{ $svc.type }}
  selector:
    {{- include "home-assistant.selectorLabels" $ | nindent 4 }}
  ports:
    {{- range $portName := keys $svc.ports | sortAlpha }}
    {{- $port := index $svc.ports $portName }}
    {{- if (default true $port.enabled) }}
    - name: {{ $portName }}
      port: {{ $port.port }}
      targetPort: {{ $portName }}
      protocol: {{ $port.protocol }}
    {{- end }}
    {{- end }}
{{- end }}
{{- end }}
