apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "home-assistant.fullname" . }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "home-assistant.fullname" . }}-headless
  replicas: {{ .Values.replicaCount }}
  podManagementPolicy: {{ .Values.podManagementPolicy }}
  updateStrategy:
    {{- toYaml .Values.updateStrategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "home-assistant.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "home-assistant.selectorLabels" . | nindent 8 }}
      {{- with .Values.pod.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      hostNetwork: {{ .Values.pod.hostNetwork }}
      {{- if .Values.pod.hostNetwork }}
      dnsPolicy: ClusterFirstWithHostNet
      {{- end }}
      serviceAccountName: {{ include "home-assistant.serviceAccountName" . }}
      {{- with .Values.global.image.pullSecrets }}
      imagePullSecrets:
        {{- range . }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      {{- with include "home-assistant.initContainers" . | trim }}
      initContainers:
        {{- . | nindent 8 }}
      {{- end }}
      containers:
        - name: home-assistant
          image: {{ include "home-assistant.image" . }}
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          {{- with include "home-assistant.containerPorts" . | trim }}
          ports:
            {{- . | nindent 12 }}
          {{- end }}
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.startupProbe.enabled }}
          startupProbe:
            {{- omit .Values.startupProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            {{- omit .Values.livenessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            {{- omit .Values.readinessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: config
              mountPath: /config
            {{- end }}
            {{- if .Values.homeAssistant.configuration.enabled }}
            - name: ha-configuration
              mountPath: /config/configuration.yaml
              subPath: configuration.yaml
              readOnly: true
            {{- end }}
            {{- range .Values.secretVolumeMounts }}
            - name: {{ .name | default .secretName }}
              mountPath: /run/secrets/{{ .mountPath | default .secretName }}
              readOnly: true
            {{- end }}
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with include "home-assistant.volumes" . | trim }}
      volumes:
        {{- . | nindent 8 }}
      {{- end }}
      {{- with .Values.pod.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pod.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pod.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
  volumeClaimTemplates:
    - metadata:
        name: config
        {{- with .Values.persistence.annotations }}
        annotations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        labels:
          {{- merge (include "home-assistant.labels" . | fromYaml) (.Values.persistence.labels | default dict) | toYaml | nindent 10 }}
      spec:
        accessModes:
          {{- toYaml .Values.persistence.accessModes | nindent 10 }}
        {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass }}
        {{- else if .Values.persistence.existingVolume }}
        storageClassName: ""
        {{- end }}
        {{- if .Values.persistence.existingVolume }}
        volumeName: {{ .Values.persistence.existingVolume }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
  {{- end }}
