apiVersion: v2
name: home-assistant
description: Home Assistant automation platform
type: application
version: 1.0.0
keywords:
  - home-assistant
  - home-automation
maintainers:
  - name: junpeng-jp
    url: https://github.com/junpeng-jp
