apiVersion: v2
name: home-assistant
description: Home Assistant automation platform
type: application
version: 0.1.0
appVersion: "2025.5.3"
keywords:
  - home-assistant
  - home-automation
maintainers:
  - name: junpeng-jp
    url: https://github.com/junpeng-jp
