{{- if .Values.ingress.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "python-matter-server.fullname" . }}
  labels:
    {{- include "python-matter-server.labels" . | nindent 4 }}
spec:
  parentRefs:
    {{- toYaml .Values.ingress.gateway.parentRefs | nindent 4 }}
  hostnames:
    {{- toYaml .Values.ingress.gateway.hostnames | nindent 4 }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "python-matter-server.fullname" . }}
          port: ws
{{- end }}
