global:
  image:
    tag: "2026.5"

persistence:
  enabled: true
  storageClass: local-path
  size: 1Gi

homeAssistant:
  gitops:
    enabled: true
    repos: []
    webhook:
      secretName: ha-gitops-webhook
      secretKey: secret
